### ISSUE TITLE
django1.9 migrate无法正确生成数据库表

### ISSUE THREAD

**Issue by zhuzhuhero** [JoneXiong/DjangoX#11]
把example数据源切换为mysql，
在django==1.9时，
migrate无法生成xadmin_*相关数据表

经测试，django==1.7时，syncdb可以生成
![image](https://cloud.githubusercontent.com/assets/25426806/22414359/ca2757ca-e6f9-11e6-9562-8abe0483f425.png)

**Comment by zhuzhuhero** [comment]
补充，django==1.8，也正常

**Comment by TonyMistark** [comment]
试试：
python manage.py makemigrations xadmin
