### ISSUE TITLE
支持django1.10版本吗

### ISSUE THREAD

**Issue by Cooper-Min** [JoneXiong/DjangoX#13]
目前使用的环境为python3.5+django1.10,运行了一下，发现运行不了
报错：
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by LucanusWorm** [comment]
版本问题，Python版本为2.7.*

**Comment by JoneXiong** [comment]
django1.10支持，但 Python3暂不支持，会尽快支持上的，欢迎一起完善
