### ISSUE TITLE
python3版本问题

### ISSUE THREAD

**Issue by bxlkm** [JoneXiong/DjangoX#24]
运行run.cmd出现以下错误    
models.ImageField: {'widget': widgets.AdminFileWidget},
AttributeError: module 'xadmin.widgets' has no attribute 'AdminFileWidget'

**Comment by TonyMistark** [comment]
feature-python3分支Python3.x还在兼容测试中，暂时不能用于生产，欢迎一起来完善！

**Comment by JoneXiong** [comment]
master主分支已合并兼容Py2和Py3
