### ISSUE TITLE
是否支持的python3.5版本

### ISSUE THREAD

**Issue by linchengzhi** [JoneXiong/DjangoX#5]
如题。你好，djangox很好用，但是测试的时候发现好像不支持python3.5，是否可以支持一下。

**Comment by JoneXiong** [comment]
@linchengzhi 好的，会尽快做相关支持，还请一起来完善！

**Comment by JoneXiong** [comment]
支持python 的分支 feature-python3  持续跟进中

**Comment by JoneXiong** [comment]
master主分支已合并兼容Py2和Py3

**Comment by linchengzhi** [comment]
虽然项目早搞定了，但还是赞一个。加油
